### ISSUE TITLE
Image links not updated

### ISSUE THREAD

**Issue by dlip** [cetra3/mdcollate#1]
If there is a relative image link in intro/intro.md

```
$ find
README.md
intro/intro.md
intro/assets/pic.jpg
```

```
$ cat intro/intro.md
![](./assets/pic.jpg)
```

```
$ mdcollate README.md > collated.md
$ cat collated.md
![](./assets/pic.jpg)
```

Then the image link should be updated to `![](./intro/assets/pic.jpg)`

**Comment by cetra3** [comment]
Yep that should be working as you say, but might not be.  I'll have a look

**Comment by cetra3** [comment]
@dlip I've checked this out with the following structure and it appears to be working for me:

[issue.zip](https://github.com/cetra3/mdcollate/files/2285033/issue.zip)

I get the following output:

```markdown
$ mdcollate README.md

<p id="README.md" class="next_file"></p>



[Intro](#intro_intro.md)
<p id="intro_intro.md" class="next_file"></p>



![](intro/assets/logo.png)
```

Is there anything different you are doing that hasn't been mentioned yet?

**Comment by dlip** [comment]
I think it's because of the way the images are in our doc, I think this is non-standard anyway:

```![](./image.jpg "alt text")```

**Comment by cetra3** [comment]
Ah yep, should probably update the regex or use a more robust MD parser to cover that case and the reference style case as well.
